SELECT * FROM MEMBER;
ALTER TABLE MEMBER MODIFY password varchar2(200);
UPDATE MEMBER SET PASSWORD = '+lhdichR3TOKcNz1Naoqkv7ng23Wr/EiZYPojgmWKT8WvACcZSgm4PxccGaVoDzdzjcvE57/TROVnabx9dPqvg==';

--현재 회원의 1번부터 10번까지 출력하기
SELECT * FROM MEMBER WHERE ROWNUM BETWEEN 3 AND 10; 

SELECT * FROM (
		SELECT ROWNUM AS RNUM, M.* 
		FROM (
			SELECT * FROM MEMBER
		) M)
WHERE RNUM BETWEEN 1 AND 10;

SELECT COUNT(*) FROM MEMBER;


SELECT * FROM (
		SELECT ROWNUM AS RNUM, M.* 
		FROM (
			SELECT * FROM MEMBER WHERE $COL LIKE ?
		) M)
WHERE RNUM BETWEEN 1 AND 10;


SELECT * FROM NOTICE ORDER BY NOTICE_NO;







